import type { Restaurant } from "@/types/restaurant";

export const mockRestaurants: Restaurant[] = [
  {
    id: "1",
    name: "정든집",
    category: "한식",
    imageUrl: "https://picsum.photos/seed/jeongdeun/480/360",
    oneLineReview: "가격 대비 만족도 최고, 밑반찬까지 정성스러워요",
    landmarkText: "을지로3가역 4번 출구 도보 3분",
    reviewCount: 214,
    trustScore: 93,
    saveCount: 512,
  },
  {
    id: "2",
    name: "카페 모먼트",
    category: "카페/디저트",
    imageUrl: "https://picsum.photos/seed/moment/480/360",
    oneLineReview: "디저트와 음료 비주얼 다 만족, 분위기 조용해서 작업하기 좋아요",
    landmarkText: "성수역 3번 출구 도보 6분",
    reviewCount: 98,
    trustScore: 89,
    saveCount: 341,
  },
  {
    id: "3",
    name: "숯불가",
    category: "고깃집",
    imageUrl: "https://picsum.photos/seed/sutbulga/480/360",
    oneLineReview: "고기 굽기 상태 완벽, 인원 대비 음식량도 넉넉해요",
    landmarkText: "강남역 11번 출구 도보 5분",
    reviewCount: 356,
    trustScore: 95,
    saveCount: 782,
  },
  {
    id: "4",
    name: "포차 한잔",
    category: "술집/주점",
    imageUrl: "https://picsum.photos/seed/hanjan/480/360",
    oneLineReview: "안주 퀄리티가 술집 수준이 아니에요, 혼술도 편하게 가능",
    landmarkText: "홍대입구역 9번 출구 도보 4분",
    reviewCount: 127,
    trustScore: 87,
    saveCount: 265,
  },
  {
    id: "5",
    name: "분식대장",
    category: "분식/패스트푸드",
    imageUrl: "https://picsum.photos/seed/bunsik/480/360",
    oneLineReview: "떡볶이 매운맛 조절 가능, 세트 메뉴 구성이 알차요",
    landmarkText: "신촌역 2번 출구 도보 2분",
    reviewCount: 183,
    trustScore: 91,
    saveCount: 420,
  },
  {
    id: "6",
    name: "이랑국수",
    category: "한식",
    imageUrl: "https://picsum.photos/seed/irang/480/360",
    oneLineReview: "국물이 깊고 재방문 의사 100%, 서비스도 친절해요",
    landmarkText: "종각역 1번 출구 도보 7분",
    reviewCount: 271,
    trustScore: 94,
    saveCount: 603,
  },
  {
    id: "7",
    name: "브루잉랩",
    category: "카페/디저트",
    imageUrl: "https://picsum.photos/seed/brewinglab/480/360",
    oneLineReview: "원두 향이 좋고 매장 청결도가 높아요, 데이트 코스로 추천",
    landmarkText: "합정역 5번 출구 도보 3분",
    reviewCount: 142,
    trustScore: 90,
    saveCount: 298,
  },
  {
    id: "8",
    name: "마당숯불",
    category: "고깃집",
    imageUrl: "https://picsum.photos/seed/madang/480/360",
    oneLineReview: "모임 장소로 딱 좋고 직원분들이 굽는 것까지 도와줘요",
    landmarkText: "건대입구역 2번 출구 도보 8분",
    reviewCount: 199,
    trustScore: 92,
    saveCount: 455,
  },
];
